name: Update awesome list

on:
  workflow_dispatch:
  schedule:
    # 每周更新（UTC 周日 00:00）
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Awesome generator
        uses: simonecorsi/mawesome@v2
        with:
          template-path: "template/README.ejs"
          api-token: ${{ secrets.API_TOKEN }}
          github-email: me@yunyoujun.cn
          github-name: ${{ github.repository_owner }}
